### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by nickzuber** [reasonml-editor/vscode-reasonml#124]
I've installed this plugin in VSCode and nothing changes when I view my ReasonML files.

I don't think anything's wrong with my merlin installation on my machine because merlin works just fine in VSCode when I open an OCaml file.

My `.merlin` files looks like

```
####{BSB GENERATED: NO EDIT
FLG -ppx '/Users/nick/projects/TrackRS/node_modules/bs-platform/bin/reactjs_jsx_ppx_2.exe'
FLG -ppx /Users/nick/projects/TrackRS/node_modules/bs-platform/bin/bsppx.exe
S /Users/nick/projects/TrackRS/node_modules/bs-platform/lib/ocaml
B /Users/nick/projects/TrackRS/node_modules/bs-platform/lib/ocaml
FLG -nostdlib -no-alias-deps -color always
FLG -w -40+6+7+27+32..39+44+45
S /Users/nick/projects/TrackRS/node_modules/bs-react-native/lib/ocaml
B /Users/nick/projects/TrackRS/node_modules/bs-react-native/lib/ocaml
S /Users/nick/projects/TrackRS/node_modules/reason-react/lib/ocaml
B /Users/nick/projects/TrackRS/node_modules/reason-react/lib/ocaml
S re
B lib/bs/re
####BSB GENERATED: NO EDIT}
```

and I'm editing ReasonML files in the `re/` directory (which is explicitly sourced in my `.merlin` file). 

In my VSCode settings I have

```json
{
    "reason.path.ocamlmerlin": "/Users/nick/.opam/system/bin/ocamlmerlin",
    "reason.formatOnSave": true
}
```

Any idea what could be causing this? I don't get any errors or anything, rather just _nothing_ happens.

**Comment by freebroccolo** [comment]
I'm not sure what could be causing this if it's working with OCaml. I don't current use the extension with Bucklescript so maybe someone else can comment. @chenglou @jchavarri?

**Comment by jchavarri** [comment]
@nickzuber Just to be sure, when you say it works with OCaml, do you mean it works with `vscode-reasonml` extension? Or do you have [`hackwaly.ocaml`](https://marketplace.visualstudio.com/items?itemName=hackwaly.ocaml) installed?

Also, have you followed [these steps](https://reasonml.github.io/guide/editor-tools/global-installation) in the Reason docs to add support for editors?

**Comment by nickzuber** [comment]
@jchavarri I've installed reason through OPAM (via your link). Also I fear this might be a problem with [bs-react-native](https://github.com/reasonml-community/bs-react-native) since I only have this problem when I work in an app with this set up — if I use `bsb -init my-first-app -theme basic-reason` or something then it works fine.

It also might help to say that it's specifically the static analysis that isn't working. The plugin will still suggest reason keywords and try to autocomplete etc but will not statically analyze any of my reason files (no type tooltips on hover, no red underline for obvious syntax mistakes or type errors).

**Comment by freebroccolo** [comment]
@nickzuber can you give this another try with the latest version of the plugin (`1.0.11`) and see if it makes a difference?

**Comment by johannth** [comment]
I ran into this issue yesterday when VSCode auto updated the plugin to 1.0.13. I'm running on VSCode 1.18.0, reason-cli 3.0.1 and MacOS Sierra.

It started working again if I downgraded the plugin to 1.0.10.

The symptoms are that the plugin is stuck on [loading] in the bottom left corner. By sprinkling logs into the plugin source code I found out that it never gets past 

```
yield languageClient.onReady();
```

in https://github.com/reasonml-editor/vscode-reasonml/blob/master/src/client/index.ts

I also noticed that `ErrorHandler.closed` gets called. I experimented with throwing an exception there and got this stacktrace:

![](https://cdn.discordapp.com/attachments/235941706116235276/380279185433952256/image.png)

Hope this helps!

**Comment by freebroccolo** [comment]
@johannth are you using nvm?

**Comment by johannth** [comment]
No but I'm using [n](https://github.com/tj/n). Do you think it could be causing it?

**Comment by freebroccolo** [comment]
@johannth I'm not certain but it seems to be a common theme that people having problems after the last few updates are using both `reason-cli` and `nvm` or something similar.

One of the recent changes I made was to launch commands in a login shell with `spawn`. The reason a login shell is sometimes needed is because if the user has tools (like `ocamlmerlin`) installed through `opam`, they need to have the opam environment initialized for the tools to be in their path.

When the user runs `opam init`, it will offer to modify one of their shell init scripts like `~/.profile`. Under Linux in most cases this will mean that the opam environment will not be initialized outside of a login shell. So for instance, `sh -c ocamlmerlin` will fail but `sh -cl ocamlmerlin` will work.

Now, the opam initialization stuff isn't directly relevant when the tools are installed through `reason-cli`, but it might be the case `nvm` and similar tools are causing the environment to not be setup as expected under a login shell.

It looks like what I'm going to have to do is modify the logic for how processes are launched to try several different approaches until one of them works. Ideally this shouldn't be necessary but as it stands there are too many different factors that can impact whether or not the external processes launch successfully depending on how people have installed the tools and what platform and shell they are using.

The most reliable approach would probably be to just use `opam config exec`, but this isn't going to work for people that are just using the bucklescript tooling because `bs-platform` doesn't include `opam` AFAIK.

**Comment by freebroccolo** [comment]
@johannth please try the `1.0.14` extension release and see if it fixes the problem for you.

**Comment by jonlaing** [comment]
Unfortunately `1.0.14` didn't fix my issues. I get type signatures on all but one of my files, and no `refmt` on save.

This is my `.merlin`:

```
####{BSB GENERATED: NO EDIT
B lib/bs
FLG -open Gerber
FLG -ppx /Users/jonlaing/projects/gerber/node_modules/bs-platform/bin/bsppx.exe
S /Users/jonlaing/projects/gerber/node_modules/bs-platform/lib/ocaml
B /Users/jonlaing/projects/gerber/node_modules/bs-platform/lib/ocaml
FLG -nostdlib -no-alias-deps -color always
FLG -w -30-40+6+7+27+32..39+44+45+101
S src
B lib/bs/src
####BSB GENERATED: NO EDIT}
```

Notice that it says `-open Gerber`. I have one file with the same name, and that's the only file in which type signatures don't show up, so I don't know if that's what's screwing it up. Let me know if you need more information.

**Comment by jonlaing** [comment]
Okay, so someone on the `#editorsupport` channel helped me with the formatting issue. You need to set `editor.formatOnSave` as well as `reason.formatOnSave`. I still have that weird issue with that one file not cooperating, but this is a great improvement. Interestingly, if I take out the `open` line in my `.merlin` that file starts working again, but I feel kinda skittish about manually editing that file. If anyone has any thoughts about that, let me know.

**Comment by johannth** [comment]
@freebroccolo 1.0.14 worked for me. Thanks for the great work!

**Comment by freebroccolo** [comment]
I'm going to go ahead and close this just to tidy up the issues list. If someone has further problems, please open another issue.

**Comment by cabproject** [comment]
It works with plugin version 1.7.7 . 
1.7.8 again has a problem.
