### ISSUE TITLE
clearDiagnostics error upon build.

### ISSUE THREAD

**Issue by jordwalke** [reasonml-editor/vscode-reasonml#143]
On a fresh checkout, `npm run build` produces this error:

```
src/client/command/doClearDiagnostics.ts(9,42): error TS2339: Property 'clearDiagnostics' does not exist on type 'typeof "/Users/jwalke/github/vscode-reasonml/node_modules/ocaml-language-server/lib/remote/client"'.

9   languageClient.onRequest(remote.client.clearDiagnostics, () => {
                                           ~~~~~~~~~~~~~~~~
```

I also notice I receive some errors in the output panel of VSCode that seem related.

**Comment by freebroccolo** [comment]
This is likely due to the fact that by default the `npm install` will grab the released `ocaml-language-server` but you need to build against the development one. If you do `npm link` in the `ocaml-language-server` directory (after installing dependencies and compiling) and then `npm link ocaml-language-server` in the `vscode-reasonml` directory, it should work if you try to rebuild.

**Comment by jordwalke** [comment]
Thanks, that did the trick.
