### ISSUE TITLE
Create an OCaml extension

### ISSUE THREAD

**Issue by lpw25** [reasonml-editor/vscode-reasonml#151]
Since the reason team has [requested the deprecation of the OCaml VS Code extension](https://github.com/hackwaly/vscode-ocaml/pull/115) in favour of this extension could you please make this extension available using an OCaml-based name as well. Ideally it would just be another name for the same extension -- so that installing "Reason" would automatically install "OCaml" -- but if that's not possible then just making the extension available under both names would probably be fine.

Currently, anyone trying to use OCaml with VS code finds [the only obviously relevant extension with a "DEPRECATED" notice](https://marketplace.visualstudio.com/search?term=ocaml&target=VSCode&category=All%20categories&sortBy=Relevance). This extension is 7th on the list and has no obvious connection to OCaml. It does not make for a good impression of OCaml and even gives the vague impression that OCaml is deprecated in favour of Reason.

**Comment by jordwalke** [comment]
I think that the "deprecation" of the other OCaml plugin was a little premature - I don't think that PR should have been merged so quickly because there are some features not yet implemented in `vscode-reasonml` such as the debugger integration.

**Comment by jordwalke** [comment]
I'll have to check with @hackwaly, but I wonder if it's more correct to say that the plugin is not maintained? I'll send a PR with whatever is accurate. I think that either way, making a separate OCaml plugin that uses the same ocaml-language-server behind the scenes is the way to go.

**Comment by freebroccolo** [comment]
Thanks for the feedback.

Creating a separate plugin is something I thought about originally but at the time I didn't want to create confusion or anything like that. Maybe it's time to revisit that.

From a political perspective I think it probably makes sense to split the extension. However, there are a number of technical and practical downsides to doing that. I'm not entirely sure it will be a good idea in the long run but it bears further consideration.

**Comment by yminsky** [comment]
Would it be terrible to name it the OCaml/Reason or Reason/OCaml plugin? Anything to make it a bit more discoverable would be nice.

**Comment by freebroccolo** [comment]
> Would it be terrible to name it the OCaml/Reason or Reason/OCaml plugin? Anything to make it a bit more discoverable would be nice.

In principle a rename could be another solution but I'm not sure if it's actually possible to rename the existing extension in such a way that it would significantly impact the search ranking.

In the meantime though I've just made some changes to the package metadata which should hopefully improve the situation.

**Comment by freebroccolo** [comment]
Below is a screenshot of what the search results look like now:

<img width="962" alt="search" src="https://user-images.githubusercontent.com/151197/34599999-9bca690c-f1b2-11e7-81e7-4b8ec74c678c.png">

**Comment by yminsky** [comment]
Hmm. It is still pretty confusing that you need to pick the lovely,
distinctive Reason logo to get OCaml support.

Does Leo's idea of a separate package that just requires the Reason package
work? That would be a lot clearer, I think.

On Jan 5, 2018 2:53 AM, "Darin Morrison" <notifications@github.com> wrote:

Below is a screenshot of what the search results look like now:

[image: search]
<https://user-images.githubusercontent.com/151197/34599999-9bca690c-f1b2-11e7-81e7-4b8ec74c678c.png>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/reasonml-editor/vscode-reasonml/issues/151#issuecomment-355493523>,
or mute the thread

**Comment by freebroccolo** [comment]
> Hmm. It is still pretty confusing that you need to pick the lovely, distinctive Reason logo to get OCaml support.

Yeah, it's not ideal. Maybe another stop gap improvement would be to show the two logos side by side or something. I'm not sure.

> Does Leo's idea of a separate package that just requires the Reason package work? That would be a lot clearer, I think.

It should work in theory. There may be some complications depending on exactly how the extension boundaries are drawn and where exactly the extension logic is split across the two packages.

Once I get the few remaining issues fixed in the WIP language server refactorings (with WSL support), I will come back to this issue and try to work out the better long term solution.

**Comment by yminsky** [comment]
If we put the two logos side by side and the two names side by side, I think that's probably enough.

Anyway, thanks for looking in to this!

**Comment by freebroccolo** [comment]
Since there hasn't been any more feedback from the OP (@lpw25) I guess I will consider this resolved.
