### ISSUE TITLE
merlin does not show most informative type

### ISSUE THREAD

**Issue by bobzhang** [reasonml-editor/vscode-reasonml#179]
<img width="363" alt="screen shot 2018-03-01 at 2 41 58 pm" src="https://user-images.githubusercontent.com/747051/36830504-d6b13050-1d5e-11e8-8070-d6fec68bedb3.png">

See the pic above, it inferred the type as "'_a -> '_b option" which is incorrect, the project is built correctly, ideally, it should output "J.expression -> J.expression option"

**Comment by freebroccolo** [comment]
I suspect this may be due to the so-called "verbosity" feature of merlin. Some commands when run multiple times will produce more refined information. In emacs you can run the typing command several times and it will expand the type.

It's a little bit difficult to handle this well currently in the language server because the handling of merlin requests is asynchronous.

I was working on a branch that would address this by allowing the behavior for handling merlin requests to be modified on a per-request basis (so that the typing requests can be repeated atomically in the merlin queue) but it's not merged yet and needs some more development before it's ready.

If you want to do some investigation you can add some logging [here](https://github.com/freebroccolo/ocaml-language-server/blob/master/src/bin/server/processes/merlin.ts#L62-L67) and [here](https://github.com/freebroccolo/ocaml-language-server/blob/master/src/bin/server/processes/merlin.ts#L84-L86). You will need to build the `ocaml-language-server` then `yarn link`, then install dependencies for this extension and finally `yarn link ocaml-language-server`, `yarn run build`, and load the extension with F5.

I'd suggest checking to see if you actually get a different result in emacs first though.

**Comment by bobzhang** [comment]
I suspect my merlin does not understand external cmt files, but it seems to me that the .merlin is correct, it used to work but these days it did not work any more, may be some unintentional upgrade breaking things

**Comment by freebroccolo** [comment]
If you can make a small self contained project I can take a look at it. Maybe @let-def has some ideas.

**Comment by bobzhang** [comment]
it seems that merlin could not handle cmt files generated by the native and bs compiler at the same time. I will close this issue, but I suggest it would be nice to enhance the debuggability when merlin does not work
