### ISSUE TITLE
Code block is highlighted with blue overlay on focus

### ISSUE THREAD

**Issue by tigp** [reasonml-editor/vscode-reasonml#209]
Hi guys, thanks  for the great package.

If I click on the code block it becomes blue, is it possible to somehow disable this behaviour?

![screenshot 2018-05-11 02 03 21](https://user-images.githubusercontent.com/24852530/39900069-b59ce600-54bf-11e8-86d4-db9d17fcb28e.png)

Thank you

**Comment by freebroccolo** [comment]
@tigp I'm not sure why that happens but as far as I am aware there shouldn't be anything in the extension itself that causes that behavior. It might be something specific to the theme you are using.

Can you test to see if it happens when you use a different theme?

Can you you try disabling other extensions and see if it still happens?

**Comment by makasimenator** [comment]
I disabled it by adding "editor.occurrencesHighlight": false to User Settings.

**Comment by konmik** [comment]
Why closed? I've just got this issue, spent some times trying to figure out the reason(ml).
