### ISSUE TITLE
Can we use merlin and ocaml in WSL for reasonml ?

### ISSUE THREAD

**Issue by mprevot** [reasonml-editor/vscode-reasonml#213]
For some reason the extension doesn't work, nevertheless I got opam, merlin, ocaml installed in WSL (GNU in Windows 10). (I'm doing cross-platform development; actually only vscode is on windows, the rest is on WSL).

Using vscode version 1.24.0 x64 on Windows 10.

Here extracts of my vscode configuration:

```
    "files.associations": {
        "*.mlp": "ocaml"
    },
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\bash.exe",
    "reason.diagnostics.tools": [
        "merlin",
        "bsb"
    ],
    "editor.formatOnSave": true,
    "reason.codelens.enabled": true,
```

Is there a way to make this work ? (merlin in particular)

**Comment by mprevot** [comment]
[solved]

I had to use the dedicated extension **OCaml and Reason IDE - for WSL,  raiscui **
and then make sure that `ocamlmerlin`'s directory was in the `$PATH`.

Hope this will help.

**Comment by freebroccolo** [comment]
Unfortunately we don't fully support WSL yet in this extension because it breaks certain features unless the path is translated back and forth from windows to unix format as we communicate with merlin. It is possible to get certain basic features enabled using workarounds such as in the package you mentioned and there is also a thread that describes how to do it in the Reason repository.

Hopefully this will be addressed properly in the next major version of the language server.
