### ISSUE TITLE
Type-checker only runs over the current file.

### ISSUE THREAD

**Issue by anisjonischkeit** [reasonml-editor/vscode-reasonml#226]
Currently when the type-checker runs on save it only runs on the current file. If the types in other files don't match up anymore because of this you do not see that there are errors. It also works the other way around. When you change a file that fixes type errors in other files, the old type errors are still shown.

<img width="292" alt="screen shot 2018-06-13 at 7 07 37 pm" src="https://user-images.githubusercontent.com/22971353/41341507-310370d8-6f3d-11e8-9923-4afdac3033bd.png">

In the image above I have fixed the error however it is still shown until I close and reopen the file.

Steps to reproduce:
- have two reason files, `A.re` and `B.re`. `A.re` calls a function in `B.re`. 
- open A.re and B.re so that they are both open.
- change the function in `B.re` to make it return a different type which won't work where `A.re` is using it's output.
- go back to the `A.re` file but don't see any errors.
- close `A.re` and open it again and now see the errors

**Comment by freebroccolo** [comment]
This is an unfortunate limitation due to the way that Merlin works, which is the tool we use to gather the diagnostics such as type errors. Merlin does not have a global view of the project at this point in time and there isn't an efficient way for the editor to work around that. It is possible to use `bsb` (from Bucklescript) instead and it should take into account changes in other files. That means you will need to be using Bucklescript though (or switch to `bsb-native`). I don't use those configurations myself so someone else could perhaps provide more detail. cc @jchavarri

**Comment by anisjonischkeit** [comment]
I am using Bucklescript so If anyone has anymore information on how to set this up that would be great.

**Comment by freebroccolo** [comment]
@anisjonischkeit You can enable bsb as mentioned under the "Configurations" section in the README. For other configuration issues, if you join the discord channel (see [here](https://github.com/reasonml-editor/vscode-reasonml#discussion)) there are usually people around that can help.
