### ISSUE TITLE
Support code formatting for OCaml

### ISSUE THREAD

**Issue by Khady** [reasonml-editor/vscode-reasonml#68]
I believe there is support of code formatting for reason using refmt. I would like to have the support of ocp-indent for the OCaml code. With the possibility to format all the document, only my selection or only one line.

I wonder if this should be done in this extension or if it's better to have a new extension for ocp-indent.

**Comment by freebroccolo** [comment]
There is at least preliminary support for ocp-indent implemented in the server. It should show up when you have an OCaml document open if you search the command panel for "format document". I haven't tested it recently but I think it should still be working. You can see how it is integrated [here](https://github.com/freebroccolo/ocaml-language-server/blob/e46df9a26118c3613ff5ccba35ea4848e3bc5a11/src/server/feature/documentFormatting.ts#L12).

**Comment by Khady** [comment]
Indeed it works for the whole document. Thank you.

The reason I would like to be able to launch it only on a line or a block or it use it to manage the indentation locally is that I can't always format a whole file. For example when I contribute to an open source project that doesn't follow a specific indentation convention, I want my new code to have a correct indentation but I don't want to change the rest of the file.

**Comment by freebroccolo** [comment]
As I recall, the server does support indenting ranges too, but it looks like I may not have exposed that to the client since it was not released yet. You can see it [here](https://github.com/freebroccolo/ocaml-language-server/blob/9b1562632c44654da3d1453c865573300457047f/src/server/command/getFormatted.ts#L20-L46).

Anyway, it should be possible to support different approaches to indenting. If you just want to indent a specific line, it might need to be set up as a hotkey though because I don't think the language server conventions provide a built-in interface for that style.

Eventually there should be an option to enable automatic/electric indentation as you type as well. There's a capability in the server for that but I am not using it yet.

**Comment by carlsagan21** [comment]
As [Ocamlformat](https://github.com/ocaml-ppx/ocamlformat) is adapted in [Infer](https://github.com/facebook/infer), I think it is the time to put Ocamlformat in the list of supporting formatters. Any ideas?

**Comment by freebroccolo** [comment]
Both `ocp-indent` and `refmt` are now supported. There is an [issue](https://github.com/freebroccolo/ocaml-language-server/issues/50) in the server repo for `ocamlformat`.
