### ISSUE TITLE
Could comment wrap / unwrap selected text (if any)

### ISSUE THREAD

**Issue by desmond-dsouza** [reasonml-editor/vscode-reasonml#77]
Rather than having two commands for commenting full line vs. selected text (seems to be called Block Comment & Line Comment), is it possible for a single command to check if there is selected text & choose accordingly?

**Comment by freebroccolo** [comment]
Those comment commands come from the editor core of VS Code and I don't think their behavior can be changed by an extension in the way you are suggesting. You might want to open an issue in the vscode repo itself about this.

I think it would be possible to implement a new command ("auto comment" or something) that does what you want but it would probably be best to put it in a new extension since it wouldn't be specific to ocaml/reason.

**Comment by freebroccolo** [comment]
Closing this since it's more of an upstream issue.
